---
name: OpenTofu T3 J4 Apply

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: "Type APPLY to confirm OpenTofu apply"
        required: true
        type: string

permissions:
  actions: read
  contents: read
  security-events: write

env:
  CONFIG_DIRECTORY: teraform-salle3-jour4
  AWS_REGION: eu-west-1
  TF_VAR_db_app_password: ${{ secrets.DB_APP_PASSWORD }}

jobs:
  opentofu-apply:
    name: OpenTofu Salle 3 Jour 4 format, validate, plan and apply
    runs-on: ubuntu-latest

    steps:
      - name: Validate apply confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_apply }}" != "APPLY" ]; then
            echo "You must type APPLY to run this workflow."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check OpenTofu formatting
        run: tofu fmt -check -recursive
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize TFLint
        run: tflint --init
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Run TFLint
        run: tflint
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.CONFIG_DIRECTORY }}
        continue-on-error: true

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"
          category: "trivy-t3-j4"

      - name: OpenTofu init
        run: tofu init -input=false
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: OpenTofu validate
        run: tofu validate
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: OpenTofu plan
        run: tofu plan -input=false -out=tfplan
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: OpenTofu apply
        run: tofu apply -input=false -auto-approve tfplan
        working-directory: ${{ env.CONFIG_DIRECTORY }}
